---
- name: Deploy sshd config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify:
    - Reload sshd
  tags:
    - ssh

- name: Ensure sshd is up and running
  service:
    name: ssh
    state: started
  tags:
    - ssh
