---
- name: include install tasks
  include_tasks: install_{{ ansible_distribution|lower }}.yml
  tags:
    - ssh

- include: config.yml

- include: users.yml
  when: openssh_ssh_users is defined or openssh_ssh_users_password is defined

- include: keys.yml
  when: openssh_ssh_users is defined

- include: ufw.yml
